### ISSUE TITLE
How just receive the unreceived message?

### ISSUE THREAD

**Issue by wanlinus** [nats-io/stan.java#122]
I just want to receive the unreceived message, deliverAllAvailable to receive all messages startWithLastReceived last message

**Comment by aricart** [comment]
@wanlinus what you are looking for is a durable subscriber. See https://github.com/nats-io/java-nats-streaming#durable-subscriptions

**Comment by wanlinus** [comment]
I want receive message is similar to use startWithLastReceived except the last received message

**Comment by sasbury** [comment]
I don't understand the question? How is the durable with startWithLastReceived not what you need?

**Comment by wanlinus** [comment]
startWithLastReceived will have one more message that I don't need

**Comment by sasbury** [comment]
Let me make an example, to be sure I get what you mean...

Suppose the channel has A, B, C in it.

You want to subscribe to the channel and get no messages.

At some point a publisher puts D in the channel, making it A, B, C, D.

Your subscriber gets D.

Is this the scenario?

**Comment by sasbury** [comment]
One option, that you may not have looked at, is setting the initial message with time or a time offset, this is different than using the "last received" as it will not send messages that went into the channel earlier.
