### ISSUE TITLE
Queue Groups Support?

### ISSUE THREAD

**Issue by cemremengu** [nats-io/stan.java#126]
What is the equivalent of queue groups for the java client specifically for the code:

https://github.com/nats-io/stan.go#queue-groups

**Comment by aricart** [comment]
The method for a queue subscription has this signature:

`Subscription subscribe(String subject, String queue, MessageHandler cb)
            throws IOException, InterruptedException, TimeoutException;`

**Comment by cemremengu** [comment]
That signature cannot be resolved for some reason:

```java
    nats.subscribe("subject", "queue", new MessageHandler() {
          public void onMessage(Message m) {
            System.out.printf("Received a message: %s\n", m.getData());
          }
        });
```


Only available ones are:

`subscribe(String subject, String queue)`
`subscribe(String subject)`

**Comment by cemremengu** [comment]
Nevermind, I needed to use streaming connection factory, apologies.

**Comment by sasbury** [comment]
No worries, we are in the process of updating the doc to have more examples. Somehow this one slipped. The Java doc should have the right signatures.
