### ISSUE TITLE
Usage of reply subject in io.nats.streaming.Message class

### ISSUE THREAD

**Issue by Manuri** [nats-io/stan.java#128]
AFAIU,
1. NATS Streaming server keeps the messages in the log regardless of the presence of a subscriber
2. When a publisher, publishes a message, it will get an Ack from the server.
3. When a subscriber receives a message, it will get acknowledge that to the server.

Also, it seems request-reply pattern is not meant to be implemented with NATS Streaming server.
(Please correct if any of the above is wrong)

So, what is the usage of [`reply` subject field ](https://github.com/nats-io/stan.java/blob/master/src/main/java/io/nats/streaming/Message.java#L113)in [io.nats.streaming.Message](https://github.com/nats-io/stan.java/blob/2.1.6/src/main/java/io/nats/streaming/Message.java) class?

**Comment by sasbury** [comment]
I talked to the streaming maintainer. That field is a left over from when streaming had a req-reply pattern. The field should be empty and unused.

I haven't removed it because that would be a breaking API change.

Sorry for any confusion.

**Comment by Manuri** [comment]
Thanks a lot for the explanation!
