### ISSUE TITLE
Synchronous method does not throw exception when message publishing is not possible.

### ISSUE THREAD

**Issue by MateuszPluciennik** [nats-io/stan.java#129]
Hi, 

I'm facing problem with synchronous publish method. 

I am using:
- NATS Streaming server **v0.14.3** in cluster mode (three nodes).
- java-nats-streaming **v2.1.6**
- jnats **v2.5.2**

The client **does not throw** any exception when message publishing is not possible.  

## How to reproduce issue

Test set:
- nats streaming server (in docker) with sql storage (postgres)
- java application able to make asynch and sync calls
- nats connection created with option `maxReconnects(-1)`

Steps:
- connect to nats server and create streaming connection,
- connect to database and remove client from database,
- restart nats server,
- when connection status change to RECONNECTED try to publish message with sync call

Sync method does not throw exception. There is also no client logs. Message is not delivered to nats server. The server logs message: 'Received invalid client publish message'.

Simplified connection initialization that I use in my application: 

```java
//imports

class ConnectionExample {

private StreamingConnection streamingConnection;
private Conncetion connection;
private String[] urls = new String[]{"nats://localhost:4222"};
private final String clusterId = "test-cluster"
private final String clientId = "test-client-id"
private final String username = "user"
private final String password = "pass"

public void initNatsConnection() throws IOException, InterruptedException { 
	Options o = new Options.Builder()
			.servers(urls)
			.userInfo(username, password)
			.maxReconnects(-1).build();

	connection = Nats.connect(o);

	StreamingConnectionFactory cf = new StreamingConnectionFactory(clusterId, clientId);
	cf.setNatsConnection(connection);

	streamingConnection = cf.createConnection();
}
```

**Comment by sasbury** [comment]
Making a note to myself - the issue could be related to the fact that the core publish will buffer outgoing messages during reconnect, so the publish goes out after a reconnect and may happen before the streaming is reconnected

We also need to implement the disconnect callback at the STAN level, which is new

**Comment by sasbury** [comment]
Stan does expect you to resend messages, so while there is a weird error here, it is essentially an internal thing. The client should resend if it doesn't get the ack for a publish.

**Comment by MateuszPluciennik** [comment]
The problem here is that I don't know whether message was not acked. 

`Publishes the payload specified by {@code data} to the subject specified by and blocks until an ACK or error is returned.`

How, differently than by catching an exception, can I recognize that the message was not delivered?

**Comment by martinplaner** [comment]
I just wanted to chime in an state that we're also currently facing this problem as the `StreamingConnection.publish(String subject, byte[] data)` simply does not block until the ACK or error is received (in contrast to what is stated in the documentation, as mentioned above).

Looking at the implementation ([here](https://github.com/nats-io/stan.java/blob/master/src/main/java/io/nats/streaming/StreamingConnectionImpl.java#L316) and corresponding methods) I can't quite follow how this method should block, so maybe there is simply something missing in the implementation?

I also tried to non-blocking overload of the method with a custom AckHandler and this method seems to work as expected. Every published message leads to an invocation of the handler (with the correct exception). But we really would like to use and rely on a blocking behavior.

**Comment by MateuszPluciennik** [comment]
@sasbury  Can you say what is the current status of this task?

**Comment by sasbury** [comment]
I haven't had a chance to dig in on this.

**Comment by sasbury** [comment]
Added support for disconnect callback in 1677e4efea953cbb7f1f211cdd02ff9bca3aa347

Also added support for ack handler to get information about the message to make it easier to resend using a manual ack handler.

Both will be in v2.2

**Comment by sasbury** [comment]
ok, looking at the code, i don't see a block either, i think either it never was sync or it broke some time ago. I will work on making publish block if you don't have a handler and doc it in the next release (coming this week I hope).

**Comment by sasbury** [comment]
I am putting in 2 fixes, first the fix to actually fire the ioexception on a timeout, but a backup timeout so that we don't get stuck if that logic fails. Should be in the 2.2.0  branch today if anyone has a chance to test.
