### ISSUE TITLE
Functionality to detect logical connection to streaming server.

### ISSUE THREAD

**Issue by MateuszPluciennik** [nats-io/stan.java#130]
When streaming server drop client id then messages from the client are not delivered. (https://github.com/nats-io/nats-streaming-server/issues/873)

It would be nice to have functionality that allow the client to check logical connection to streaming server.

**Comment by sasbury** [comment]
There is a new, optional "ping/pong" APi on the server for this that we need to add to the client. It will help with this.

**Comment by sasbury** [comment]
Added support for ping in 1677e4efea953cbb7f1f211cdd02ff9bca3aa347.
