### ISSUE TITLE
Add logging to java-nats-streaming

### ISSUE THREAD

**Issue by CarloWakefield** [nats-io/stan.java#131]
We are using `java-nats-streaming` in version `2.1.6` in our Java Gradle project.
Unfortunately our program freezes when running integration tests on our CI server. It freezes at this code line:

`        return streamingConnectionFactory.createConnection();`

Now I wanted to turn up logging to see where exactly it freezes inside the `StreamingConnectionFactory`. Unfortunately I haven't found any log statements in the source code.

Please add logging statements to make hunting down errors easier.

**Comment by sasbury** [comment]
The latest Nats library has some tracing you can turn on for connections, i will look at adding something similar here.
