### ISSUE TITLE
Using a version range for nats-core causes problems for users with locked dependencies

### ISSUE THREAD

**Issue by toadzky** [nats-io/stan.java#138]
Pinning or locking dependencies to specific versions is a fairly common pattern to achieve repeatable builds. In maven, when a project is released, it resolves the versions before publishing to Maven Central and committing/tagging the source, then reverts it back to the range for the next snapshot. 

Since stan.java depends on a range for nats-core in Maven Central, my builds fail every time you release an update to nats-core because we have the version of nats-core resolved and locked.

I did some googling about how to do something similar with gradle and it appears that gradle calls it "dependency locking" (https://docs.gradle.org/current/userguide/dependency_locking.html). Would it be possible to have this project lock the version of nats-core when you release it?

**Comment by sasbury** [comment]
I am automating this build, will lock the version while I am at it.

Sorry about any pain from trying to automate the nats.java build.
