### ISSUE TITLE
Correct disconnection strategy?

### ISSUE THREAD

**Issue by peng-w** [nats-io/stan.java#139]
Hello:
    I'm using nats streaming as a messaging system, where messages are persisted to redis when the network is disconnected.Wait for the nats streaming to reconnect and resend the redis saved data.

I have a few questions:
1、Nats Streaming not support automatically reconnect? How to solve?
2、The correct way to determine the disconnection is: 
  A: io.nats.streaming.Options.Builder#connectionListener?
  B: io.nats.streaming.Options.Builder#connectionLostHandler?
  C: io.nats.streaming.Options.Builder#errorListener?
  D: io.nats.streaming.StreamingConnection#pulish + ack?
  I choose D, but i don't know next step!(Am I doing it correctly?)

```java
public static void main(String[] args) throws Exception {
    StreamingConnectionFactory factory = new StreamingConnectionFactory();
    Options.Builder builder = new Options.Builder();
    builder.natsUrl("nats://localhost:4222");
    builder.clusterId("test-cluster");
    builder.clientId("producer");
    factory.setOptions(builder.build());

    StreamingConnection streamingConnection = factory.createConnection();

    int i = 1;
    while (true) {
        String message = String.format("hello: nats %d", i);
        streamingConnection.publish("Demo0001", message.getBytes(), new AckHandler() {
            @Override
            public void onAck(String nuid, Exception ex) {
                System.out.println(nuid);
                ex.printStackTrace();
            }
        });
        System.out.printf("send messaging：%s\r\n", message);
        TimeUnit.SECONDS.sleep(3);
        i++;
    }
}
```

**Comment by sasbury** [comment]
1. Use the connection lost handler to identify your nats connection went away, but also use the acks you get from publish.

**Comment by peng-w** [comment]
1、Use ackhandler to determine if the nats streaming receives a publish message
2、ConnectionLostHandler retries the operation
Is that right?

**Comment by peng-w** [comment]
@sasbury，I have an idea, Thank you very much!
