### ISSUE TITLE
Thread leak in client on "clientId already registered" Error

### ISSUE THREAD

**Issue by tjmcarthur** [nats-io/stan.java#141]
I have a second instance of my application as hot standby in a registration loop, waiting for a valid connection. The standby instance OOMs every 90 minutes to due to a thread leak. The close method in StreamingConnectionImpl.java throws a NPE setting up the for loop
`for(AckClousre ac : this.pubAckMap.values()) { ` 
since pubAckMap is null, this cause the method to bail leaving the dispatchers open with active threads.

**Comment by sasbury** [comment]
I will take a look. If you have a chance to put a PR together it might be faster, but I should be able to fix this in the next release. Sounds like we just need to skip that loop if the value is null, or pre-alloc the map.

**Comment by tjmcarthur** [comment]
ok, I will code up a fix and submit a PR this morning

**Comment by sasbury** [comment]
fixed in 2.2.3 going out today
